Bump custodian from 2023.7.22 to 2023.10.9 (#1048)
Bumps [custodian](https://github.com/materialsproject/custodian) from
2023.7.22 to 2023.10.9.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/materialsproject/custodian/releases">custodian's
releases</a>.</em></p>
<blockquote>
<h2>v2023.10.9</h2>
<h2>What's Changed</h2>
<ul>
<li>move <code>algo_tet</code> changes from
<code>UnrecoverableError</code> to <code>VaspErrorHandler</code> by <a
href="https://github.com/janosh"><code>@​janosh</code></a> in <a
href="https://redirect.github.com/materialsproject/custodian/pull/277">materialsproject/custodian#277</a></li>
<li>Add <code>ruff</code> linter by <a
href="https://github.com/janosh"><code>@​janosh</code></a> in <a
href="https://redirect.github.com/materialsproject/custodian/pull/278">materialsproject/custodian#278</a></li>
<li>Delete unused configs by <a
href="https://github.com/janosh"><code>@​janosh</code></a> in <a
href="https://redirect.github.com/materialsproject/custodian/pull/279">materialsproject/custodian#279</a></li>
<li>Fix broken link in README.md by <a
href="https://github.com/R1j1t"><code>@​R1j1t</code></a> in <a
href="https://redirect.github.com/materialsproject/custodian/pull/281">materialsproject/custodian#281</a></li>
<li>Fix <code>ruff</code> PERF401 errors by <a
href="https://github.com/janosh"><code>@​janosh</code></a> in <a
href="https://redirect.github.com/materialsproject/custodian/pull/282">materialsproject/custodian#282</a></li>
<li>Fix AttributeError NoneType has no attribute 'style' by <a
href="https://github.com/janosh"><code>@​janosh</code></a> in <a
href="https://redirect.github.com/materialsproject/custodian/pull/283">materialsproject/custodian#283</a></li>
<li>Tweak unconverged, bravais and den-/tet error handling by <a
href="https://github.com/janosh"><code>@​janosh</code></a> in <a
href="https://redirect.github.com/materialsproject/custodian/pull/284">materialsproject/custodian#284</a></li>
<li>Fix <code>MeshSymmetryErrorHandler</code> treating
<code>ISYM=-1</code> as symmetry ON by <a
href="https://github.com/janosh"><code>@​janosh</code></a> in <a
href="https://redirect.github.com/materialsproject/custodian/pull/285">materialsproject/custodian#285</a></li>
<li>Update <a
href="https://github.com/arosen93"><code>@​arosen93</code></a> to <a
href="https://github.com/Andrew-S-Rosen"><code>@​Andrew-S-Rosen</code></a>
by <a
href="https://github.com/Andrew-S-Rosen"><code>@​Andrew-S-Rosen</code></a>
in <a
href="https://redirect.github.com/materialsproject/custodian/pull/289">materialsproject/custodian#289</a></li>
<li>Fix lint errors by <a
href="https://github.com/janosh"><code>@​janosh</code></a> in <a
href="https://redirect.github.com/materialsproject/custodian/pull/290">materialsproject/custodian#290</a></li>
<li>Minor Q-Chem updates by <a
href="https://github.com/samblau"><code>@​samblau</code></a> in <a
href="https://redirect.github.com/materialsproject/custodian/pull/292">materialsproject/custodian#292</a></li>
<li>Q-Chem bug fix by <a
href="https://github.com/samblau"><code>@​samblau</code></a> in <a
href="https://redirect.github.com/materialsproject/custodian/pull/293">materialsproject/custodian#293</a></li>
<li>Delete requirements.txt by <a
href="https://github.com/Andrew-S-Rosen"><code>@​Andrew-S-Rosen</code></a>
in <a
href="https://redirect.github.com/materialsproject/custodian/pull/295">materialsproject/custodian#295</a></li>
</ul>
<h2>New Contributors</h2>
<ul>
<li><a href="https://github.com/R1j1t"><code>@​R1j1t</code></a> made
their first contribution in <a
href="https://redirect.github.com/materialsproject/custodian/pull/281">materialsproject/custodian#281</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/materialsproject/custodian/compare/v2023.7.22...v2023.10.9">https://github.com/materialsproject/custodian/compare/v2023.7.22...v2023.10.9</a></p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/materialsproject/custodian/blob/master/docs/changelog.md">custodian's
changelog</a>.</em></p>
<blockquote>
<h2>2023.10.9</h2>
<ul>
<li>PR <a
href="https://redirect.github.com/materialsproject/custodian/issues/293">#293</a>
from <a href="https://github.com/samblau"><code>@​samblau</code></a> (<a
href="https://redirect.github.com/materialsproject/custodian/issues/293">#293</a>)
A bug was introduced during the recent Minor Q-Chem updates PR:
<pre lang="diff"><code>- os.mkdir(local_scratch, exist_ok=True)
+ os.makedirs(local_scratch, exist_ok=True)
</code></pre>
I would appreciate it if a new version could please be released after
this PR is merged. Thanks!</li>
<li>PR <a
href="https://redirect.github.com/materialsproject/custodian/issues/292">#292</a>
from <a href="https://github.com/samblau"><code>@​samblau</code></a> (<a
href="https://redirect.github.com/materialsproject/custodian/issues/292">#292</a>)
This PR fixes a few bugs in the Q-Chem error handlers, adds one new
handler, adds some additional tests, and slightly extends post
processing scratch file handling.</li>
<li>PR <a
href="https://redirect.github.com/materialsproject/custodian/issues/285">#285</a>
from <a href="https://github.com/janosh"><code>@​janosh</code></a> (<a
href="https://redirect.github.com/materialsproject/custodian/issues/285">#285</a>)
7b0c061a fix <code>MeshSymmetryErrorHandler</code> treating
<code>ISYM=-1</code> as symmetry ON
72ac1213 <code>PositiveEnergyErrorHandler</code> don't decrease
<code>POTIM</code> for static calcs</li>
<li>PR <a
href="https://redirect.github.com/materialsproject/custodian/issues/284">#284</a>
from <a href="https://github.com/janosh"><code>@​janosh</code></a> (<a
href="https://redirect.github.com/materialsproject/custodian/issues/284">#284</a>)
225a1e8d UnconvergedErrorHandler only set algo to normal if ISMEAR&gt;=0
608530b2 mv custodian/feff/tests/test_handler{,s}.py
c11ab49e tweak bravais error handling in VaspErrorHandler
283fe9d2 improve den-/tet error handling in case of not using kspacing
bc022852 fix VaspErrorHandlerTest.test_bravais</li>
<li>PR <a
href="https://redirect.github.com/materialsproject/custodian/issues/283">#283</a>
from <a href="https://github.com/janosh"><code>@​janosh</code></a> (<a
href="https://redirect.github.com/materialsproject/custodian/issues/283">#283</a>)
When running VASP with <code>INCAR</code> tag <code>kspacing</code>
instead of a <code>KPOINTS</code> file and encountering
<code>brmix</code> 2 or 3 times. Reported by <a
href="https://github.com/esoteric-ephemera"><code>@​esoteric-ephemera</code></a>
in atomate2 r2SCAN workflow.</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/materialsproject/custodian/commit/edb79af9d92631be24c6731b4811263fbad05e9e"><code>edb79af</code></a>
Update dev docs</li>
<li><a
href="https://github.com/materialsproject/custodian/commit/0a233ef87a3e618a306483c176d8647add174aff"><code>0a233ef</code></a>
Fix changelog code.</li>
<li><a
href="https://github.com/materialsproject/custodian/commit/bd4c1e40847b20b4676000af21a962fab534691c"><code>bd4c1e4</code></a>
ruff . --select FURB --preview --fix</li>
<li><a
href="https://github.com/materialsproject/custodian/commit/b6142e24ac4269633ad8d26922940430e715f907"><code>b6142e2</code></a>
Delete requirements.txt (<a
href="https://redirect.github.com/materialsproject/custodian/issues/295">#295</a>)</li>
<li><a
href="https://github.com/materialsproject/custodian/commit/d0130f7b7b676585fae1af00e18457b5d64ed9e6"><code>d0130f7</code></a>
pre-commit autoupdate (<a
href="https://redirect.github.com/materialsproject/custodian/issues/294">#294</a>)</li>
<li><a
href="https://github.com/materialsproject/custodian/commit/753e54c4cf90d6190440fdf0ca79a0997acff923"><code>753e54c</code></a>
Q-Chem fix os.mkdir -&gt; os.makedirs (<a
href="https://redirect.github.com/materialsproject/custodian/issues/293">#293</a>)</li>
<li><a
href="https://github.com/materialsproject/custodian/commit/4d78d09c0d03689c6e5756d96047b5a3be2fb688"><code>4d78d09</code></a>
Minor Q-Chem updates (<a
href="https://redirect.github.com/materialsproject/custodian/issues/292">#292</a>)</li>
<li><a
href="https://github.com/materialsproject/custodian/commit/85cf4aa00825318b9ddbe9d92149c67c8abe0c4b"><code>85cf4aa</code></a>
Fix lint errors (<a
href="https://redirect.github.com/materialsproject/custodian/issues/290">#290</a>)</li>
<li><a
href="https://github.com/materialsproject/custodian/commit/9563d8f539d2ff9335000adb5953e6b023b6e1ed"><code>9563d8f</code></a>
Update <a href="https://github.com/arosen93"><code>@​arosen93</code></a>
to <a
href="https://github.com/Andrew-S-Rosen"><code>@​Andrew-S-Rosen</code></a>
(<a
href="https://redirect.github.com/materialsproject/custodian/issues/289">#289</a>)</li>
<li><a
href="https://github.com/materialsproject/custodian/commit/0c58d3fd6a5bbd76af5a58e82654444fc6d3c54d"><code>0c58d3f</code></a>
pre-commit autoupdate (<a
href="https://redirect.github.com/materialsproject/custodian/issues/288">#288</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/materialsproject/custodian/compare/v2023.7.22...v2023.10.9">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=custodian&package-manager=pip&previous-version=2023.7.22&new-version=2023.10.9)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>