Bump pymatgen from 2025.5.28 to 2025.6.14 (#2835)
[//]: # (dependabot-start)
⚠️  **Dependabot is rebasing this PR** ⚠️ 

Rebasing might not happen immediately, so don't worry if this takes some
time.

Note: if you make any changes to this PR yourself, they will take
precedence over the rebase.

---

[//]: # (dependabot-end)

Bumps [pymatgen](https://github.com/materialsproject/pymatgen) from
2025.5.28 to 2025.6.14.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/materialsproject/pymatgen/releases">pymatgen's
releases</a>.</em></p>
<blockquote>
<h2>v2025.6.14</h2>
<ul>
<li>Treat LATTICE_CONSTRAINTS as is for INCARs.</li>
<li>PR <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4425">#4425</a>
<code>JDFTXOutfileSlice.trajectory</code> revision by <a
href="https://github.com/benrich37"><code>@​benrich37</code></a>
Major changes:
<ul>
<li>feature 1: <code>JDFTXOutfileSlice.trajectory</code> is now
initialized with <code>frame_properties</code> set
-- <code>JOutStructure.properties</code> filled with relevant data for
<code>frame_properties</code>
-- More properties added to
<code>JOutStructure.site_properties</code></li>
</ul>
<h2>Todos</h2>
<ul>
<li>Remove class attributes in <code>JOutStructure</code> now redundant
to data stored in <code>JOutStructure.properties</code> and
<code>JOutStructure.site_properties</code></li>
</ul>
</li>
<li>PR <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4431">#4431</a>
Single source of truth for POTCAR directory structure by <a
href="https://github.com/esoteric-ephemera"><code>@​esoteric-ephemera</code></a>
Modifies the pymatgen CLI to use the same POTCAR library directory
structure as in <code>pymatgen.io.vasp.inputs</code> to close <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4430">#4430</a>.
Possibly breaking from the CLI side (the directory structure will
change)
Pinging <a
href="https://github.com/mkhorton"><code>@​mkhorton</code></a> since <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4424">#4424</a>
was probably motivated by similar concerns?</li>
<li>PR <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4433">#4433</a>
Speed up symmetry functions with faster <code>is_periodic_image</code>
algorithm by <a
href="https://github.com/kavanase"><code>@​kavanase</code></a>
I noticed that in some of our <code>doped</code> testing workflows,
<code>SpacegroupAnalyzer.get_primitive_standard_structure()</code> is
one of the main bottlenecks (as to be expected). One of the dominant
cost factors here is the usage of <code>is_periodic_image</code>, which
can be expensive for large structures due to many
<code>np.allclose()</code> calls.
This PR implements a small change to instead use an equivalent (but
faster) pure Python loop, which also breaks early if the tolerance is
exceeded.
In my test case, this reduced the time spent on
<code>is_periodic_image</code> (and thus
<code>SpacegroupAnalyzer.get_primitive_standard_structure()</code>) from
35s to 10s.</li>
<li>PR <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4432">#4432</a>
Fingerprint sources by <a
href="https://github.com/JaGeo"><code>@​JaGeo</code></a>
Add correct papers to tanimoto fingerprints</li>
<li>PR <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4061">#4061</a>
Fix branch directory check in
<code>io.vasp.outputs.get_band_structure_from_vasp_multiple_branches</code>
by <a
href="https://github.com/DanielYang59"><code>@​DanielYang59</code></a>
<h3>Summary</h3>
<ul>
<li>Fix branch directory check in
<code>io.vasp.outputs.get_band_structure_from_vasp_multiple_branches</code>,
to fix <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4060">#4060</a></li>
<li>[ ] Improve unit test (waiting for data, I don't have experience
with &quot;VASP multi-branch bandstructure calculation&quot;)</li>
</ul>
</li>
<li>PR <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4409">#4409</a>
Packmol constraints by <a
href="https://github.com/davidwaroquiers"><code>@​davidwaroquiers</code></a>
Added possibility to set individual constraints in packmol.
Added some sanity checks.
Added unit tests.</li>
<li>PR <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4428">#4428</a>
Fixes a bug in <code>NanoscaleStability.plot_one_stability_map</code>
and <code>plot_all_stability_map</code>. by <a
href="https://github.com/kmu"><code>@​kmu</code></a>
Major changes:
<ul>
<li>Replaced incorrect <code>ax.xlabel()</code> and
<code>ax.ylabel()</code> calls with correct <code>ax.set_xlabel()</code>
and <code>ax.set_ylabel()</code>.</li>
<li>Added <code>ax.legend()</code> to
<code>plot_all_stability_map</code> so that labels passed via
<code>ax.plot(..., label=...)</code> are displayed.</li>
<li>Added <code>test_plot()</code> to
<code>test_surface_analysis.py</code>.</li>
</ul>
</li>
<li>PR <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4424">#4424</a>
Add additional name mappings for new LDA v64 potcars by <a
href="https://github.com/mkhorton"><code>@​mkhorton</code></a>
As title.</li>
<li>PR <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4426">#4426</a>
Fix uncertainty as int for <code>EnergyAdjustment</code> by <a
href="https://github.com/DanielYang59"><code>@​DanielYang59</code></a>
<ul>
<li>Avoid <code>==</code> or <code>!=</code> for possible float
comparison</li>
<li>Fix uncertainty as int for <code>EnergyAdjustment</code> cannot
generate repr:</li>
</ul>
<pre lang="python"><code>from pymatgen.entries.computed_entries import
EnergyAdjustment
print(EnergyAdjustment(10, uncertainty=0))
</code></pre>
Gives:
<pre><code>Traceback (most recent call last):
File &quot;/Users/yang/developer/pymatgen/test_json.py&quot;, line 25,
in &lt;module&gt;
print(EnergyAdjustment(10, uncertainty=0))
File
&quot;/Users/yang/developer/pymatgen/src/pymatgen/entries/computed_entries.py&quot;,
line 108, in __repr__
return f&quot;{type(self).__name__}({name=}, {value=:.3},
{uncertainty=:.3}, {description=}, {generated_by=})&quot;
^^^^^^^^^^^^^^^^^
ValueError: Precision not allowed in integer format specifier
</code></pre>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/materialsproject/pymatgen/blob/master/docs/CHANGES.md">pymatgen's
changelog</a>.</em></p>
<blockquote>
<h2>v2025.6.14</h2>
<ul>
<li>Treat LATTICE_CONSTRAINTS as is for INCARs.</li>
<li>PR <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4425">#4425</a>
<code>JDFTXOutfileSlice.trajectory</code> revision by <a
href="https://github.com/benrich37"><code>@​benrich37</code></a>
Major changes:
<ul>
<li>feature 1: <code>JDFTXOutfileSlice.trajectory</code> is now
initialized with <code>frame_properties</code> set
-- <code>JOutStructure.properties</code> filled with relevant data for
<code>frame_properties</code>
-- More properties added to
<code>JOutStructure.site_properties</code></li>
</ul>
<h2>Todos</h2>
<ul>
<li>Remove class attributes in <code>JOutStructure</code> now redundant
to data stored in <code>JOutStructure.properties</code> and
<code>JOutStructure.site_properties</code></li>
</ul>
</li>
<li>PR <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4431">#4431</a>
Single source of truth for POTCAR directory structure by <a
href="https://github.com/esoteric-ephemera"><code>@​esoteric-ephemera</code></a>
Modifies the pymatgen CLI to use the same POTCAR library directory
structure as in <code>pymatgen.io.vasp.inputs</code> to close <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4430">#4430</a>.
Possibly breaking from the CLI side (the directory structure will
change)
Pinging <a
href="https://github.com/mkhorton"><code>@​mkhorton</code></a> since <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4424">#4424</a>
was probably motivated by similar concerns?</li>
<li>PR <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4433">#4433</a>
Speed up symmetry functions with faster <code>is_periodic_image</code>
algorithm by <a
href="https://github.com/kavanase"><code>@​kavanase</code></a>
I noticed that in some of our <code>doped</code> testing workflows,
<code>SpacegroupAnalyzer.get_primitive_standard_structure()</code> is
one of the main bottlenecks (as to be expected). One of the dominant
cost factors here is the usage of <code>is_periodic_image</code>, which
can be expensive for large structures due to many
<code>np.allclose()</code> calls.
This PR implements a small change to instead use an equivalent (but
faster) pure Python loop, which also breaks early if the tolerance is
exceeded.
In my test case, this reduced the time spent on
<code>is_periodic_image</code> (and thus
<code>SpacegroupAnalyzer.get_primitive_standard_structure()</code>) from
35s to 10s.</li>
<li>PR <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4432">#4432</a>
Fingerprint sources by <a
href="https://github.com/JaGeo"><code>@​JaGeo</code></a>
Add correct papers to tanimoto fingerprints</li>
<li>PR <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4061">#4061</a>
Fix branch directory check in
<code>io.vasp.outputs.get_band_structure_from_vasp_multiple_branches</code>
by <a
href="https://github.com/DanielYang59"><code>@​DanielYang59</code></a>
<h3>Summary</h3>
<ul>
<li>Fix branch directory check in
<code>io.vasp.outputs.get_band_structure_from_vasp_multiple_branches</code>,
to fix <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4060">#4060</a></li>
<li>[ ] Improve unit test (waiting for data, I don't have experience
with &quot;VASP multi-branch bandstructure calculation&quot;)</li>
</ul>
</li>
<li>PR <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4409">#4409</a>
Packmol constraints by <a
href="https://github.com/davidwaroquiers"><code>@​davidwaroquiers</code></a>
Added possibility to set individual constraints in packmol.
Added some sanity checks.
Added unit tests.</li>
<li>PR <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4428">#4428</a>
Fixes a bug in <code>NanoscaleStability.plot_one_stability_map</code>
and <code>plot_all_stability_map</code>. by <a
href="https://github.com/kmu"><code>@​kmu</code></a>
Major changes:
<ul>
<li>Replaced incorrect <code>ax.xlabel()</code> and
<code>ax.ylabel()</code> calls with correct <code>ax.set_xlabel()</code>
and <code>ax.set_ylabel()</code>.</li>
<li>Added <code>ax.legend()</code> to
<code>plot_all_stability_map</code> so that labels passed via
<code>ax.plot(..., label=...)</code> are displayed.</li>
<li>Added <code>test_plot()</code> to
<code>test_surface_analysis.py</code>.</li>
</ul>
</li>
<li>PR <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4424">#4424</a>
Add additional name mappings for new LDA v64 potcars by <a
href="https://github.com/mkhorton"><code>@​mkhorton</code></a>
As title.</li>
<li>PR <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4426">#4426</a>
Fix uncertainty as int for <code>EnergyAdjustment</code> by <a
href="https://github.com/DanielYang59"><code>@​DanielYang59</code></a>
<ul>
<li>Avoid <code>==</code> or <code>!=</code> for possible float
comparison</li>
<li>Fix uncertainty as int for <code>EnergyAdjustment</code> cannot
generate repr:</li>
</ul>
<pre lang="python"><code>from pymatgen.entries.computed_entries import
EnergyAdjustment
print(EnergyAdjustment(10, uncertainty=0))
</code></pre>
Gives:
<pre><code>Traceback (most recent call last):
File &quot;/Users/yang/developer/pymatgen/test_json.py&quot;, line 25,
in &lt;module&gt;
print(EnergyAdjustment(10, uncertainty=0))
File
&quot;/Users/yang/developer/pymatgen/src/pymatgen/entries/computed_entries.py&quot;,
line 108, in __repr__
return f&quot;{type(self).__name__}({name=}, {value=:.3},
{uncertainty=:.3}, {description=}, {generated_by=})&quot;
^^^^^^^^^^^^^^^^^
ValueError: Precision not allowed in integer format specifier
</code></pre>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/materialsproject/pymatgen/commit/682bfd855dd89264b0ff8d6bee4815f8834cc5ac"><code>682bfd8</code></a>
Update docs</li>
<li><a
href="https://github.com/materialsproject/pymatgen/commit/da30857f8b0d89837b317f470c383573b7d88406"><code>da30857</code></a>
Update changelog.</li>
<li><a
href="https://github.com/materialsproject/pymatgen/commit/02bed16647381092fe1c82fad30622404d385a9f"><code>02bed16</code></a>
Merge branch 'master' of github.com:materialsproject/pymatgen</li>
<li><a
href="https://github.com/materialsproject/pymatgen/commit/3de47f3660793b1fe45a0e8bbb275f42ced8f1f8"><code>3de47f3</code></a>
Treat LATTICE_CONSTRAINTS as a as-is tag for now. Fixes <a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4325">#4325</a>.</li>
<li><a
href="https://github.com/materialsproject/pymatgen/commit/234d1150b46f2114bb29af8f6036cd8c7b60f40b"><code>234d115</code></a>
<code>JDFTXOutfileSlice.trajectory</code> revision (<a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4425">#4425</a>)</li>
<li><a
href="https://github.com/materialsproject/pymatgen/commit/2b3510a72e2cdf46b33b8e84eeb745052331c9b9"><code>2b3510a</code></a>
Bump requests from 2.32.3 to 2.32.4 (<a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4434">#4434</a>)</li>
<li><a
href="https://github.com/materialsproject/pymatgen/commit/98bdb66ed7ab454cb24ea4981529d72859962cdb"><code>98bdb66</code></a>
Single source of truth for POTCAR directory structure (<a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4431">#4431</a>)</li>
<li><a
href="https://github.com/materialsproject/pymatgen/commit/5a4046b364a1a6fd23b81519e825458af772c20c"><code>5a4046b</code></a>
Speed up symmetry functions with faster <code>is_periodic_image</code>
algorithm (<a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4433">#4433</a>)</li>
<li><a
href="https://github.com/materialsproject/pymatgen/commit/ec1b63b920e286db0605214302a02e5f462c7537"><code>ec1b63b</code></a>
Fingerprint sources (<a
href="https://redirect.github.com/materialsproject/pymatgen/issues/4432">#4432</a>)</li>
<li><a
href="https://github.com/materialsproject/pymatgen/commit/aa08052fb56fd0f1bbeeb0d48f44469b67474b2b"><code>aa08052</code></a>
Fix branch directory check in
`io.vasp.outputs.get_band_structure_from_vasp_m...</li>
<li>Additional commits viewable in <a
href="https://github.com/materialsproject/pymatgen/compare/v2025.5.28...v2025.6.14">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=pymatgen&package-manager=pip&previous-version=2025.5.28&new-version=2025.6.14)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>